Search.appendIndex(
    [
                {
            "fqsen": "\\FastForward\\Config\\AggregateConfig",
            "name": "AggregateConfig",
            "summary": "Class\u0020AggregateConfig.",
            "url": "classes/FastForward-Config-AggregateConfig.html"
        },                {
            "fqsen": "\\FastForward\\Config\\AggregateConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020new\u0020instance\u0020by\u0020accepting\u0020a\u0020variadic\u0020list\u0020of\u0020configuration\u0020objects.",
            "url": "classes/FastForward-Config-AggregateConfig.html#method___construct"
        },                {
            "fqsen": "\\FastForward\\Config\\AggregateConfig\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Invokes\u0020the\u0020configuration\u0020aggregator.",
            "url": "classes/FastForward-Config-AggregateConfig.html#method___invoke"
        },                {
            "fqsen": "\\FastForward\\Config\\AggregateConfig\u003A\u003A\u0024configs",
            "name": "configs",
            "summary": "",
            "url": "classes/FastForward-Config-AggregateConfig.html#property_configs"
        },                {
            "fqsen": "\\FastForward\\Config\\ArrayConfig",
            "name": "ArrayConfig",
            "summary": "Class\u0020ArrayConfig.",
            "url": "classes/FastForward-Config-ArrayConfig.html"
        },                {
            "fqsen": "\\FastForward\\Config\\ArrayConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020the\u0020ArrayConfig\u0020instance.",
            "url": "classes/FastForward-Config-ArrayConfig.html#method___construct"
        },                {
            "fqsen": "\\FastForward\\Config\\ArrayConfig\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "Determines\u0020whether\u0020the\u0020given\u0020configuration\u0020key\u0020exists.",
            "url": "classes/FastForward-Config-ArrayConfig.html#method_has"
        },                {
            "fqsen": "\\FastForward\\Config\\ArrayConfig\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Retrieves\u0020a\u0020value\u0020from\u0020the\u0020configuration.",
            "url": "classes/FastForward-Config-ArrayConfig.html#method_get"
        },                {
            "fqsen": "\\FastForward\\Config\\ArrayConfig\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Sets\u0020configuration\u0020values\u0020into\u0020the\u0020internal\u0020data\u0020store.",
            "url": "classes/FastForward-Config-ArrayConfig.html#method_set"
        },                {
            "fqsen": "\\FastForward\\Config\\ArrayConfig\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Removes\u0020a\u0020configuration\u0020key\u0020and\u0020its\u0020associated\u0020value.",
            "url": "classes/FastForward-Config-ArrayConfig.html#method_remove"
        },                {
            "fqsen": "\\FastForward\\Config\\ArrayConfig\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "Retrieves\u0020a\u0020traversable\u0020set\u0020of\u0020flattened\u0020configuration\u0020data.",
            "url": "classes/FastForward-Config-ArrayConfig.html#method_getIterator"
        },                {
            "fqsen": "\\FastForward\\Config\\ArrayConfig\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Converts\u0020the\u0020entire\u0020configuration\u0020to\u0020an\u0020associative\u0020array.",
            "url": "classes/FastForward-Config-ArrayConfig.html#method_toArray"
        },                {
            "fqsen": "\\FastForward\\Config\\ArrayConfig\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/FastForward-Config-ArrayConfig.html#property_data"
        },                {
            "fqsen": "\\FastForward\\Config\\CachedConfig",
            "name": "CachedConfig",
            "summary": "Class\u0020CachedConfig.",
            "url": "classes/FastForward-Config-CachedConfig.html"
        },                {
            "fqsen": "\\FastForward\\Config\\CachedConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020CachedConfig\u0020wrapper.",
            "url": "classes/FastForward-Config-CachedConfig.html#method___construct"
        },                {
            "fqsen": "\\FastForward\\Config\\CachedConfig\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Invokes\u0020the\u0020configuration\u0020and\u0020returns\u0020the\u0020cached\u0020configuration\u0020data.",
            "url": "classes/FastForward-Config-CachedConfig.html#method___invoke"
        },                {
            "fqsen": "\\FastForward\\Config\\CachedConfig\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Sets\u0020configuration\u0020data.",
            "url": "classes/FastForward-Config-CachedConfig.html#method_set"
        },                {
            "fqsen": "\\FastForward\\Config\\CachedConfig\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Retrieves\u0020a\u0020configuration\u0020value\u0020by\u0020key.",
            "url": "classes/FastForward-Config-CachedConfig.html#method_remove"
        },                {
            "fqsen": "\\FastForward\\Config\\CachedConfig\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/FastForward-Config-CachedConfig.html#property_cache"
        },                {
            "fqsen": "\\FastForward\\Config\\CachedConfig\u003A\u003A\u0024defaultConfig",
            "name": "defaultConfig",
            "summary": "",
            "url": "classes/FastForward-Config-CachedConfig.html#property_defaultConfig"
        },                {
            "fqsen": "\\FastForward\\Config\\CachedConfig\u003A\u003A\u0024persistent",
            "name": "persistent",
            "summary": "",
            "url": "classes/FastForward-Config-CachedConfig.html#property_persistent"
        },                {
            "fqsen": "\\FastForward\\Config\\CachedConfig\u003A\u003A\u0024cacheKey",
            "name": "cacheKey",
            "summary": "",
            "url": "classes/FastForward-Config-CachedConfig.html#property_cacheKey"
        },                {
            "fqsen": "\\FastForward\\Config\\ConfigInterface",
            "name": "ConfigInterface",
            "summary": "Interface\u0020ConfigInterface.",
            "url": "classes/FastForward-Config-ConfigInterface.html"
        },                {
            "fqsen": "\\FastForward\\Config\\ConfigInterface\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "Determines\u0020if\u0020the\u0020specified\u0020key\u0020exists\u0020in\u0020the\u0020configuration.",
            "url": "classes/FastForward-Config-ConfigInterface.html#method_has"
        },                {
            "fqsen": "\\FastForward\\Config\\ConfigInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Retrieves\u0020a\u0020value\u0020from\u0020the\u0020configuration\u0020by\u0020key.",
            "url": "classes/FastForward-Config-ConfigInterface.html#method_get"
        },                {
            "fqsen": "\\FastForward\\Config\\ConfigInterface\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Sets\u0020a\u0020configuration\u0020value\u0020or\u0020merges\u0020an\u0020array\u0020or\u0020ConfigInterface.",
            "url": "classes/FastForward-Config-ConfigInterface.html#method_set"
        },                {
            "fqsen": "\\FastForward\\Config\\ConfigInterface\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Removes\u0020a\u0020configuration\u0020key\u0020and\u0020its\u0020associated\u0020value.",
            "url": "classes/FastForward-Config-ConfigInterface.html#method_remove"
        },                {
            "fqsen": "\\FastForward\\Config\\ConfigInterface\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Exports\u0020the\u0020configuration\u0020as\u0020a\u0020nested\u0020associative\u0020array.",
            "url": "classes/FastForward-Config-ConfigInterface.html#method_toArray"
        },                {
            "fqsen": "\\FastForward\\Config\\Container\\ConfigContainer",
            "name": "ConfigContainer",
            "summary": "Class\u0020ConfigContainer.",
            "url": "classes/FastForward-Config-Container-ConfigContainer.html"
        },                {
            "fqsen": "\\FastForward\\Config\\Container\\ConfigContainer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020new\u0020ConfigContainer\u0020instance.",
            "url": "classes/FastForward-Config-Container-ConfigContainer.html#method___construct"
        },                {
            "fqsen": "\\FastForward\\Config\\Container\\ConfigContainer\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "Determines\u0020whether\u0020the\u0020container\u0020can\u0020return\u0020an\u0020entry\u0020for\u0020the\u0020given\u0020identifier.",
            "url": "classes/FastForward-Config-Container-ConfigContainer.html#method_has"
        },                {
            "fqsen": "\\FastForward\\Config\\Container\\ConfigContainer\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Retrieves\u0020an\u0020entry\u0020of\u0020the\u0020container\u0020by\u0020its\u0020identifier.",
            "url": "classes/FastForward-Config-Container-ConfigContainer.html#method_get"
        },                {
            "fqsen": "\\FastForward\\Config\\Container\\ConfigContainer\u003A\u003AisResolvedByContainer\u0028\u0029",
            "name": "isResolvedByContainer",
            "summary": "Determines\u0020whether\u0020the\u0020given\u0020identifier\u0020is\u0020resolved\u0020internally\u0020by\u0020the\u0020container\u0020itself.",
            "url": "classes/FastForward-Config-Container-ConfigContainer.html#method_isResolvedByContainer"
        },                {
            "fqsen": "\\FastForward\\Config\\Container\\ConfigContainer\u003A\u003AALIAS",
            "name": "ALIAS",
            "summary": "",
            "url": "classes/FastForward-Config-Container-ConfigContainer.html#constant_ALIAS"
        },                {
            "fqsen": "\\FastForward\\Config\\Container\\ConfigContainer\u003A\u003A\u0024config",
            "name": "config",
            "summary": "",
            "url": "classes/FastForward-Config-Container-ConfigContainer.html#property_config"
        },                {
            "fqsen": "\\FastForward\\Config\\DirectoryConfig",
            "name": "DirectoryConfig",
            "summary": "Class\u0020DirectoryConfig.",
            "url": "classes/FastForward-Config-DirectoryConfig.html"
        },                {
            "fqsen": "\\FastForward\\Config\\DirectoryConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020DirectoryConfig\u0020instance.",
            "url": "classes/FastForward-Config-DirectoryConfig.html#method___construct"
        },                {
            "fqsen": "\\FastForward\\Config\\DirectoryConfig\u003A\u003APATTERN",
            "name": "PATTERN",
            "summary": "",
            "url": "classes/FastForward-Config-DirectoryConfig.html#constant_PATTERN"
        },                {
            "fqsen": "\\FastForward\\Config\\DirectoryConfig\u003A\u003A\u0024directory",
            "name": "directory",
            "summary": "",
            "url": "classes/FastForward-Config-DirectoryConfig.html#property_directory"
        },                {
            "fqsen": "\\FastForward\\Config\\DirectoryConfig\u003A\u003A\u0024cachedConfigFile",
            "name": "cachedConfigFile",
            "summary": "",
            "url": "classes/FastForward-Config-DirectoryConfig.html#property_cachedConfigFile"
        },                {
            "fqsen": "\\FastForward\\Config\\Exception\\ContainerNotFoundException",
            "name": "ContainerNotFoundException",
            "summary": "Class\u0020ContainerNotFoundException.",
            "url": "classes/FastForward-Config-Exception-ContainerNotFoundException.html"
        },                {
            "fqsen": "\\FastForward\\Config\\Exception\\ContainerNotFoundException\u003A\u003AforKey\u0028\u0029",
            "name": "forKey",
            "summary": "Creates\u0020a\u0020new\u0020exception\u0020instance\u0020for\u0020a\u0020missing\u0020configuration\u0020key.",
            "url": "classes/FastForward-Config-Exception-ContainerNotFoundException.html#method_forKey"
        },                {
            "fqsen": "\\FastForward\\Config\\Exception\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "Class\u0020InvalidArgumentException.",
            "url": "classes/FastForward-Config-Exception-InvalidArgumentException.html"
        },                {
            "fqsen": "\\FastForward\\Config\\Exception\\InvalidArgumentException\u003A\u003AforNonStringKeyWithValue\u0028\u0029",
            "name": "forNonStringKeyWithValue",
            "summary": "Thrown\u0020when\u0020the\u0020key\u0020is\u0020not\u0020a\u0020string\u0020but\u0020a\u0020value\u0020is\u0020provided.",
            "url": "classes/FastForward-Config-Exception-InvalidArgumentException.html#method_forNonStringKeyWithValue"
        },                {
            "fqsen": "\\FastForward\\Config\\Exception\\InvalidArgumentException\u003A\u003AforUnreadableDirectory\u0028\u0029",
            "name": "forUnreadableDirectory",
            "summary": "Thrown\u0020when\u0020a\u0020given\u0020directory\u0020does\u0020not\u0020exist\u0020or\u0020is\u0020not\u0020readable.",
            "url": "classes/FastForward-Config-Exception-InvalidArgumentException.html#method_forUnreadableDirectory"
        },                {
            "fqsen": "\\FastForward\\Config\\Exception\\InvalidArgumentException\u003A\u003AforUnreadableFile\u0028\u0029",
            "name": "forUnreadableFile",
            "summary": "Thrown\u0020when\u0020a\u0020given\u0020file\u0020does\u0020not\u0020exist\u0020or\u0020is\u0020not\u0020readable.",
            "url": "classes/FastForward-Config-Exception-InvalidArgumentException.html#method_forUnreadableFile"
        },                {
            "fqsen": "\\FastForward\\Config\\Exception\\InvalidArgumentException\u003A\u003AforUnwritableFile\u0028\u0029",
            "name": "forUnwritableFile",
            "summary": "Thrown\u0020when\u0020a\u0020configuration\u0020file\u0020is\u0020not\u0020writable.",
            "url": "classes/FastForward-Config-Exception-InvalidArgumentException.html#method_forUnwritableFile"
        },                {
            "fqsen": "\\FastForward\\Config\\Exception\\InvalidArgumentException\u003A\u003AforInvalidConfigFile\u0028\u0029",
            "name": "forInvalidConfigFile",
            "summary": "Thrown\u0020when\u0020a\u0020configuration\u0020file\u0020does\u0020not\u0020return\u0020an\u0020array.",
            "url": "classes/FastForward-Config-Exception-InvalidArgumentException.html#method_forInvalidConfigFile"
        },                {
            "fqsen": "\\FastForward\\Config\\config\u0028\u0029",
            "name": "config",
            "summary": "Creates\u0020a\u0020unified\u0020configuration\u0020object\u0020from\u0020various\u0020sources.",
            "url": "namespaces/fastforward-config.html#function_config"
        },                {
            "fqsen": "\\FastForward\\Config\\configCache\u0028\u0029",
            "name": "configCache",
            "summary": "Creates\u0020a\u0020cached\u0020configuration\u0020object\u0020from\u0020various\u0020sources.",
            "url": "namespaces/fastforward-config.html#function_configCache"
        },                {
            "fqsen": "\\FastForward\\Config\\configDir\u0028\u0029",
            "name": "configDir",
            "summary": "Creates\u0020a\u0020directory\u002Dbased\u0020configuration\u0020provider.",
            "url": "namespaces/fastforward-config.html#function_configDir"
        },                {
            "fqsen": "\\FastForward\\Config\\configProvider\u0028\u0029",
            "name": "configProvider",
            "summary": "Creates\u0020a\u0020configuration\u0020from\u0020a\u0020list\u0020of\u0020Laminas\u002Dstyle\u0020configuration\u0020providers.",
            "url": "namespaces/fastforward-config.html#function_configProvider"
        },                {
            "fqsen": "\\FastForward\\Config\\configFile\u0028\u0029",
            "name": "configFile",
            "summary": "Creates\u0020a\u0020PHP\u0020file\u0020configuration\u0020provider.",
            "url": "namespaces/fastforward-config.html#function_configFile"
        },                {
            "fqsen": "\\FastForward\\Config\\Helper\\ConfigHelper",
            "name": "ConfigHelper",
            "summary": "Class\u0020ConfigHelper.",
            "url": "classes/FastForward-Config-Helper-ConfigHelper.html"
        },                {
            "fqsen": "\\FastForward\\Config\\Helper\\ConfigHelper\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020constructor\u0020is\u0020private\u0020to\u0020prevent\u0020instantiation\u0020of\u0020the\u0020class.",
            "url": "classes/FastForward-Config-Helper-ConfigHelper.html#method___construct"
        },                {
            "fqsen": "\\FastForward\\Config\\Helper\\ConfigHelper\u003A\u003AisAssoc\u0028\u0029",
            "name": "isAssoc",
            "summary": "Determines\u0020if\u0020the\u0020provided\u0020value\u0020is\u0020an\u0020associative\u0020array.",
            "url": "classes/FastForward-Config-Helper-ConfigHelper.html#method_isAssoc"
        },                {
            "fqsen": "\\FastForward\\Config\\Helper\\ConfigHelper\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "Normalizes\u0020a\u0020configuration\u0020array\u0020using\u0020dot\u0020notation\u0020delimiters.",
            "url": "classes/FastForward-Config-Helper-ConfigHelper.html#method_normalize"
        },                {
            "fqsen": "\\FastForward\\Config\\Helper\\ConfigHelper\u003A\u003Aflatten\u0028\u0029",
            "name": "flatten",
            "summary": "Flattens\u0020a\u0020nested\u0020configuration\u0020array\u0020into\u0020a\u0020dot\u002Dnotated\u0020traversable\u0020set.",
            "url": "classes/FastForward-Config-Helper-ConfigHelper.html#method_flatten"
        },                {
            "fqsen": "\\FastForward\\Config\\LamiasConfigAggregatorConfig",
            "name": "LamiasConfigAggregatorConfig",
            "summary": "Class\u0020LamiasConfigAggregatorConfig.",
            "url": "classes/FastForward-Config-LamiasConfigAggregatorConfig.html"
        },                {
            "fqsen": "\\FastForward\\Config\\LaminasConfigAggregatorConfig",
            "name": "LaminasConfigAggregatorConfig",
            "summary": "Class\u0020LaminasConfigAggregatorConfig.",
            "url": "classes/FastForward-Config-LaminasConfigAggregatorConfig.html"
        },                {
            "fqsen": "\\FastForward\\Config\\LaminasConfigAggregatorConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020the\u0020configuration\u0020aggregator.",
            "url": "classes/FastForward-Config-LaminasConfigAggregatorConfig.html#method___construct"
        },                {
            "fqsen": "\\FastForward\\Config\\LaminasConfigAggregatorConfig\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Aggregates\u0020configuration\u0020from\u0020the\u0020provided\u0020sources\u0020and\u0020returns\u0020a\u0020unified\u0020configuration\u0020object.",
            "url": "classes/FastForward-Config-LaminasConfigAggregatorConfig.html#method___invoke"
        },                {
            "fqsen": "\\FastForward\\Config\\LaminasConfigAggregatorConfig\u003A\u003A\u0024providers",
            "name": "providers",
            "summary": "",
            "url": "classes/FastForward-Config-LaminasConfigAggregatorConfig.html#property_providers"
        },                {
            "fqsen": "\\FastForward\\Config\\LaminasConfigAggregatorConfig\u003A\u003A\u0024cachedConfigFile",
            "name": "cachedConfigFile",
            "summary": "",
            "url": "classes/FastForward-Config-LaminasConfigAggregatorConfig.html#property_cachedConfigFile"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait",
            "name": "LazyLoadConfigTrait",
            "summary": "Trait\u0020LazyLoadConfigTrait.",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Implementing\u0020class\u0020MUST\u0020define\u0020the\u0020__invoke\u0028\u0029\u0020method\u0020to\u0020return\u0020a\u0020ConfigInterface\u0020instance.",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html#method___invoke"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Retrieves\u0020a\u0020configuration\u0020value\u0020by\u0020key.",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html#method_get"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "Checks\u0020for\u0020existence\u0020of\u0020a\u0020configuration\u0020key.",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html#method_has"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Sets\u0020configuration\u0020data.",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html#method_set"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Removes\u0020a\u0020configuration\u0020key.",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html#method_remove"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Exports\u0020the\u0020entire\u0020configuration\u0020to\u0020an\u0020array.",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html#method_toArray"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "Retrieves\u0020an\u0020iterator\u0020for\u0020traversing\u0020the\u0020configuration\u0020data.",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html#method_getIterator"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait\u003A\u003AgetConfig\u0028\u0029",
            "name": "getConfig",
            "summary": "Retrieves\u0020or\u0020initializes\u0020the\u0020configuration\u0020instance.",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html#method_getConfig"
        },                {
            "fqsen": "\\FastForward\\Config\\LazyLoadConfigTrait\u003A\u003A\u0024config",
            "name": "config",
            "summary": "",
            "url": "classes/FastForward-Config-LazyLoadConfigTrait.html#property_config"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig",
            "name": "PhpFileConfig",
            "summary": "Class\u0020PhpFileConfig.",
            "url": "classes/FastForward-Config-PhpFileConfig.html"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020a\u0020PhpFileConfig\u0020instance.",
            "url": "classes/FastForward-Config-PhpFileConfig.html#method___construct"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Invokes\u0020the\u0020configuration\u0020and\u0020returns\u0020the\u0020configuration\u0020data.",
            "url": "classes/FastForward-Config-PhpFileConfig.html#method___invoke"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Sets\u0020configuration\u0020data.",
            "url": "classes/FastForward-Config-PhpFileConfig.html#method_set"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Removes\u0020a\u0020configuration\u0020key\u0020and\u0020its\u0020associated\u0020value.",
            "url": "classes/FastForward-Config-PhpFileConfig.html#method_remove"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003AloadConfig\u0028\u0029",
            "name": "loadConfig",
            "summary": "Loads\u0020the\u0020configuration\u0020from\u0020the\u0020file\u0020or\u0020default\u0020configuration.",
            "url": "classes/FastForward-Config-PhpFileConfig.html#method_loadConfig"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003Amutate\u0028\u0029",
            "name": "mutate",
            "summary": "Executes\u0020a\u0020persistent\u0020mutation\u0020under\u0020an\u0020exclusive\u0020process\u0020lock.",
            "url": "classes/FastForward-Config-PhpFileConfig.html#method_mutate"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003Adump\u0028\u0029",
            "name": "dump",
            "summary": "Dumps\u0020the\u0020configuration\u0020array\u0020to\u0020the\u0020PHP\u0020file.",
            "url": "classes/FastForward-Config-PhpFileConfig.html#method_dump"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003AresolveTargetFile\u0028\u0029",
            "name": "resolveTargetFile",
            "summary": "Resolves\u0020the\u0020target\u0020file\u0020path,\u0020resolving\u0020symlinks\u0020to\u0020their\u0020canonical\u0020target.",
            "url": "classes/FastForward-Config-PhpFileConfig.html#method_resolveTargetFile"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003A\u0024file",
            "name": "file",
            "summary": "",
            "url": "classes/FastForward-Config-PhpFileConfig.html#property_file"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003A\u0024persistent",
            "name": "persistent",
            "summary": "",
            "url": "classes/FastForward-Config-PhpFileConfig.html#property_persistent"
        },                {
            "fqsen": "\\FastForward\\Config\\PhpFileConfig\u003A\u003A\u0024defaultConfig",
            "name": "defaultConfig",
            "summary": "",
            "url": "classes/FastForward-Config-PhpFileConfig.html#property_defaultConfig"
        },                {
            "fqsen": "\\FastForward\\Config\\RecursiveDirectoryConfig",
            "name": "RecursiveDirectoryConfig",
            "summary": "Class\u0020RecursiveDirectoryConfig.",
            "url": "classes/FastForward-Config-RecursiveDirectoryConfig.html"
        },                {
            "fqsen": "\\FastForward\\Config\\RecursiveDirectoryConfig\u003A\u003APATTERN",
            "name": "PATTERN",
            "summary": "",
            "url": "classes/FastForward-Config-RecursiveDirectoryConfig.html#constant_PATTERN"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\FastForward\\Config",
            "name": "Config",
            "summary": "",
            "url": "namespaces/fastforward-config.html"
        },                {
            "fqsen": "\\FastForward",
            "name": "FastForward",
            "summary": "",
            "url": "namespaces/fastforward.html"
        },                {
            "fqsen": "\\FastForward\\Config\\Container",
            "name": "Container",
            "summary": "",
            "url": "namespaces/fastforward-config-container.html"
        },                {
            "fqsen": "\\FastForward\\Config\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/fastforward-config-exception.html"
        },                {
            "fqsen": "\\FastForward\\Config\\Helper",
            "name": "Helper",
            "summary": "",
            "url": "namespaces/fastforward-config-helper.html"
        }            ]
);
